version: '2'

vars:
  REPO: ynishi
  TARGET: netlify-cli-docker
  VERSION: 13.1.0-alpine3.10-2.21.0

tasks:
  build:
    desc: build docker image
    cmds:
      - docker build -t {{.TARGET}} . --no-cache
      - docker build -t {{.REPO}}/{{.TARGET}}:latest .
      - docker build -t {{.REPO}}/{{.TARGET}}:{{.VERSION}} .
  push:
    desc: push docker image
    cmds:
      - docker push {{.REPO}}/{{.TARGET}}:latest
      - docker push {{.REPO}}/{{.TARGET}}:{{.VERSION}}

